[workspace]
resolver = "3"
members = [
    "example",
    "fprime_macros",
    "fprime_internal",
    "fprime_build",
    "fprime_dictionary",
    "fprime_core"
]

[profile.release]
lto = true
opt-level = 'z'
