[package]
name = "fprime_macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true
name = "fprime_macros"
path = "src/lib.rs"

[dependencies]
proc-macro2 = "1.0.103"
quote = "1.0.41"
syn = { version = "2.0.108", features = ["full"] }
